apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: skylark
  namespace: prod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: skylark
        env: prod
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx1024m -Dlogback.configurationFile=skylark/logback.xml -Dconfig.resource=skylark/production.conf
        image: quay.io/whisk/skylark-api:v2.23
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/status/_healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: skylark
        ports:
        - containerPort: 8081
          name: service
      imagePullSecrets:
      - name: quay-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: air
  namespace: prod
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: air
        env: prod
    spec:
      containers:
      - name: air
        image: quay.io/whisk/air-frontend:feature-x3-b3052
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          # an http probe
          httpGet:
            path: /status/_healthz
            port: 80
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: air-ssl-proxy-secret
      imagePullSecrets:
      - name: quay-key