apiVersion: v1
kind: Service
metadata:
  name: skylark-dev
  namespace: default
  labels:
    app: skylark
    env: dev
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: service
    protocol: TCP
    name: http
  selector:
    app: skylark
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: skylark
  namespace: default
  labels:
    app: skylark-default
    env: dev
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: service
    protocol: TCP
    name: http
  selector:
    app: skylark
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: air
  namespace: default
  labels:
    app: air
    env: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: air
    env: dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: air
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - secretName: tls-secret
  rules:
  - host: dev.joinair.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: skylark-dev
          servicePort: 8081
      - path: /
        backend:
          serviceName: air
          servicePort: 80