apiVersion: v1
kind: Service
metadata:
  name: air-mailer
  namespace: prod
  labels:
    app: air-mailer
    env: prod
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: service
    protocol: TCP
    name: http
  selector:
    app: air-mailer
    env: prod